### ISSUE TITLE
Add X-Runtime header with total execution time of a request

### ISSUE THREAD

**Issue by nhocki** [c4milo/handlers#2]
I have no idea where or how to add that, any pointers?

**Comment by c4milo** [comment]
This information should be provided already by the logger handler, it appears as latency in the logs.

**Comment by nhocki** [comment]
Yes, I want that in the HTTP response as the `X-Runtime` header.

**Comment by c4milo** [comment]
@nhocki normally one would write another HTTP handler for that, following the middleware mindset.

**Comment by c4milo** [comment]
@nhocki LOL, I thought we were discussing in the go-google-proxy repo. :family:

**Comment by c4milo** [comment]
I would put it after this line: https://github.com/c4milo/handlers/blob/master/logger/logger.go#L103

**Comment by c4milo** [comment]
as `RequestLatency`

**Comment by nhocki** [comment]
@c4milo my question about that line is... at that point, has the handler function been called? ... And yeah, I also think another middleware is better, I just have no idea what I'm doing :joy:

**Comment by c4milo** [comment]
@nhocki I took a more careful look at this. Sending a response header with latency is a tricky one as we don't really know how long it took until this returns: https://github.com/c4milo/handlers/blob/master/logger/logger.go#L108, making it too late for us to append another header as the response was sent already.

**Comment by c4milo** [comment]
>I also think another middleware is better, I just have no idea what I'm doing :joy:
me neither :)
